version: "3"

volumes:
  db_data: {}
  wordpress_data:
    driver: local

services:
   mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    ports:
      - "3306:3306"
    volumes:
      - 'db_data:/bitnami/mariadb'
    env_file: .env      

  wordpress:
    image: "docker.io/bitnami/wordpress:5-debian-10"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "wordpress_data:/bitnami/wordpress"
    depends_on:
      - mariadb
    env_file: .env
