version: "3"

volumes:
  db_data: {}
  wordpress_data:
    driver: local

services:
  maria:
    image: mariadb:10.3
    container_name: "maria-srv"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    image: "docker.io/bitnami/wordpress:5-debian-10"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "wordpress_data:/bitnami/wordpress"
    depends_on:
      - mariadb
    env_file: .env
