version: "3"

volumes:
  db_data: {}

  maria:
    image: mariadb:10.3
    container_name: "maria-srv"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
